const DATA_URL = "data/prices.json";
const ITEMS = [["apple","Apple","🍎","Apple"],["pear","Pear","🍐","Pear"],["plum","Plum","🟣","Plum"],["peach","Peach","🍑","Peach"],["tomato","Tomato","🍅","Tomato"],["cabbage","Cabbage","🥬","Cabbage"],["cauliflower","Cauliflower","🥦","Cauliflo."],["potato","Potato","🥔","Potato"],["onion","Onion","🧅","Onion"],["carrot","Carrot","🥕","Carrot"]];
let data=null, report=""; const $=id=>document.getElementById(id);
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const price=r=>{const n=Number(r?.[`${$("priceType").value}_price_kg`]);return Number.isFinite(n)?n:null}; const fmt=n=>n==null?"-":n.toFixed(1);
function buildReport(){const mains=data.main_markets||[], comps=data.comparison_markets||[];const available=ITEMS.filter(([key])=>Object.values(data.prices[key]||{}).some(Boolean));let t=`📊 *Mandi Prices (₹/kg) — Kullu district*\n${data.display_date}\n\n`;for(const [key,name,emoji] of available){t+=`${emoji} *${name}*\n`;for(const m of mains)t+=`   ${m.short}: ${fmt(price(data.prices[key]?.[m.display]))}\n`;t+="\n"}t+="🌍 *Other Market Comparison*\n\n";let comparisonCount=0;for(const [key,name,emoji] of available){const rows=comps.map(m=>[m.display,price(data.prices[key]?.[m.display])]).filter(([,n])=>n!=null);if(!rows.length)continue;comparisonCount++;t+=`${emoji} *${name}*\n`;for(const [market,n] of rows)t+=`   ${market}: ${fmt(n)}\n`;t+="\n"}if(!comparisonCount)t+="No comparison prices available today.\n\n";return t+"💰 Prices are per kg (converted from ₹/quintal)\n📌 Source: AGMARKNET, Govt of India"}
function render(){if(!data)return;report=buildReport();$("output").value=report;$("copyBtn").disabled=false;const current=data.date===today();$("status").textContent=data.status==="error"?"🔴 Data update failed":current?"🟢 Updated today":"🟡 Data not updated yet";$("lastUpdated").textContent=`${current?"":"⚠️ Showing last successfully updated data: "}${data.display_date} ${new Date(data.updated_at).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata",hour:"2-digit",minute:"2-digit"})} IST`;$("debug").textContent=JSON.stringify({records:data.verification,unmatched_api_markets:data.unmatched_api_markets,unmatched_api_commodities:data.unmatched_api_commodities},null,2)}
async function load(){$("updateBtn").disabled=true;$("status").textContent="⏳ Updating…";try{const r=await fetch(`${DATA_URL}?t=${Date.now()}`);if(!r.ok)throw Error();data=await r.json();render()}catch{$("status").textContent="🔴 No price data published yet";$("lastUpdated").textContent="⚠️ Government data update failed. Run the update workflow and try again."}finally{$("updateBtn").disabled=false}}
async function copy(){try{if(navigator.clipboard)await navigator.clipboard.writeText(report);else{$("output").select();document.execCommand("copy")}$("copyBtn").textContent="✅ Copied!";setTimeout(()=>$("copyBtn").textContent="📋 Copy WhatsApp Report",2000)}catch{$("status").textContent="⚠️ Copy failed — select the report and copy it manually."}}
$("updateBtn").addEventListener("click",load);$("copyBtn").addEventListener("click",copy);$("priceType").addEventListener("change",render);load();
