#!/usr/bin/env node
/* Cloud fetcher. Mirrors the proven files9 AGMARKNET request flow, but publishes
   only the seven public commodities and keeps modal/min/max values. */
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const API='https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070';
const KEY=process.env.AGMARKNET_API_KEY;
const LOCATIONS=[
 ['Himachal Pradesh','Kullu'],['Himachal Pradesh','Mandi'],['NCT of Delhi','Delhi'],
 ['Maharashtra','Nashik'],['Jammu and Kashmir','Jammu'],['Rajasthan','Jaipur']
];
const ITEMS=[['apple','Apple','🍎',['apple']],['pear','Pear','🍐',['pear']],['plum','Plum','🟣',['plum']],['peach','Peach','🍑',['peach']],['tomato','Tomato','🍅',['tomato']],['cabbage','Cabbage','🥬',['cabbage']],['cauliflower','Cauliflower','🥦',['cauliflower']]];
const MARKETS=[
 ['SMY Bhuntar',['bhuntar','smy bhuntar','pmy bhuntar']],['PMY Kullu',['pmy kullu']],['SMY Khegsu',['khegsu','smy khegsu','pmy khegsu']],['Kullu',['kullu','kullu mandi']],
 ['Bandrol',['bandrol','smy bandrol','pmy bandrol']],['Takoli',['takoli','smy takoli','pmy takoli']],['Banjar',['banjar','smy banjar','pmy banjar']],['Sundernagar',['sundernagar','sunder nagar']],['Ner Chowk',['ner chowk','nerchowk']],['Delhi',['delhi','delhi mandi','azadpur','azadpur mandi']],['Nashik',['nashik','nasik','pimpalgaon']],['Jammu',['jammu','jammu mandi','narwal']],['Jaipur',['jaipur','jaipur mandi']]
];
const MAIN=MARKETS.slice(0,4).map(x=>x[0]), OTHER=MARKETS.slice(4).map(x=>x[0]);
const norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'').replace(/^(smy|pmy)/,'');
const apiDate=d=>`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`;
const isoDate=s=>{const [d,m,y]=s.split('/').map(Number);return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`};
function itemFor(raw){const n=norm(raw);return ITEMS.find(x=>x[3].some(a=>norm(a)===n)||n.startsWith(norm(x[1])))||null}
function marketFor(raw){const n=norm(raw);return MARKETS.find(x=>x[1].some(a=>norm(a)===n||n.includes(norm(a))||norm(a).includes(n)))||null}
async function page(state,district,date,offset){const u=new URL(API);for(const [k,v] of Object.entries({'api-key':KEY,format:'json',limit:'100',offset:String(offset),'filters[state]':state,'filters[district]':district,'filters[arrival_date]':date}))u.searchParams.set(k,v);let last;for(let i=0;i<3;i++){try{const r=await fetch(u,{signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}catch(e){last=e;if(i<2)await new Promise(x=>setTimeout(x,1200*(i+1)))}}throw Error(`${state}/${district}: ${last.message}`)}
async function scope(state,district,date){let all=[],offset=0;for(;;){const p=await page(state,district,date,offset),batch=p.records||[];all.push(...batch);const total=Number(p.total||all.length);if(!batch.length||all.length>=total||batch.length<100)break;offset+=batch.length}return all}
async function fetchDate(date){const settled=await Promise.allSettled(LOCATIONS.map(x=>scope(...x,date)));const records=[];let failures=0;settled.forEach(x=>x.status==='fulfilled'?records.push(...x.value):failures++);if(failures===LOCATIONS.length)throw Error('All AGMARKNET requests failed');return records}
function num(x){const n=Number(String(x??'').replace(/,/g,''));return Number.isFinite(n)&&n>=0?n:null}
function makePayload(records,date,now){const prices={};ITEMS.forEach(([k])=>prices[k]=Object.fromEntries(MARKETS.map(([m])=>[m,null])));const verification=[],unknownMarkets=new Set(),unknownItems=new Set();for(const r of records){const item=itemFor(r.commodity), market=marketFor(r.market);if(!item){if(r.commodity)unknownItems.add(r.commodity);continue}if(!market){if(r.market)unknownMarkets.add(r.market);continue}const [key,name]=item,display=market[0];const q={min:num(r.min_price),max:num(r.max_price),modal:num(r.modal_price)};const rec={market:display,api_market:r.market,commodity:name,api_commodity:r.commodity,date:r.arrival_date||date,min_price_quintal:q.min,max_price_quintal:q.max,modal_price_quintal:q.modal,min_price_kg:q.min==null?null:q.min/100,max_price_kg:q.max==null?null:q.max/100,modal_price_kg:q.modal==null?null:q.modal/100,source:'AGMARKNET / data.gov.in'};if(!prices[key][display]||prices[key][display].modal_price_quintal==null&&rec.modal_price_quintal!=null){prices[key][display]=rec;verification.push(rec)}}const today=apiDate(now),chosen=isoDate(date);return {schema_version:2,date:chosen,display_date:date,is_today:chosen===isoDate(today),updated_at:now.toISOString(),source:'AGMARKNET / Govt. of India',price_unit:'₹/kg',conversion:'₹/quintal ÷ 100',commodities:ITEMS.map(([key,name,emoji])=>({key,name,emoji})),main_markets:MAIN,comparison_markets:OTHER,prices,verification,unmatched_api_markets:[...unknownMarkets].sort(),unmatched_api_commodities:[...unknownItems].sort(),warning:chosen===isoDate(today)?'':"Today's data not available — latest available data shown."}}
function write(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(value,null,2)+'\n');fs.renameSync(tmp,file)}
(async()=>{if(!KEY)throw Error('AGMARKNET_API_KEY is required');const now=new Date(),forced=process.env.MANDI_DATE;const dates=[];if(forced){const [y,m,d]=forced.split('-').map(Number);dates.push(new Date(y,m-1,d))}else for(let i=0;i<6;i++){const d=new Date(now);d.setDate(d.getDate()-i);dates.push(d)}let payload;for(const d of dates){const date=apiDate(d);console.log(`Checking ${date}...`);try{const records=await fetchDate(date);console.log(`  ${records.length} records`);if(records.length){payload=makePayload(records,date,now);if(payload.verification.length)break}}catch(e){console.error(`  ${e.message}`);if(forced)throw e}}if(!payload||!payload.verification.length)throw Error('No matching AGMARKNET records found');write(path.join(ROOT,'data/prices.json'),payload);write(path.join(ROOT,'data/dates',payload.date+'.json'),payload);const datesDir=path.join(ROOT,'data','dates');write(path.join(ROOT,'data','dates.json'),fs.readdirSync(datesDir).filter(x=>/^\d{4}-\d{2}-\d{2}\.json$/.test(x)).map(x=>x.slice(0,-5)).sort().reverse());console.log(`Published ${payload.display_date}; matched ${payload.verification.length} records`);ITEMS.forEach(([k,n,e])=>console.log(e,n,Object.values(payload.prices[k]).filter(Boolean).length))})().catch(e=>{console.error('FETCH FAILED:',e.message);process.exit(1)})
